import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cidien",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/Cidien.png", type: "image/png" }],
    shortcut: "/Cidien.png",
    apple: "/Cidien.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen flex-col">
          <header className="sticky top-0 z-[100] flex h-12 shrink-0 items-center overflow-visible border-b border-gray-200 bg-white/95 px-4 backdrop-blur supports-[backdrop-filter]:bg-white/80 sm:h-14 sm:px-6">
            <Link
              href="/"
              className="inline-flex max-w-full items-center rounded-md outline-none ring-offset-2 focus-visible:ring-2 focus-visible:ring-emerald-600"
            >
              <span className="inline-flex origin-left scale-[1.28] sm:scale-[1.22]">
                <Image
                  src="/Cidien.png"
                  alt="Cidien"
                  width={720}
                  height={234}
                  sizes="(max-width: 640px) 90vw, 420px"
                  className="h-8 w-auto max-w-[min(78vw,18rem)] object-contain object-left sm:h-9 sm:max-w-[min(85vw,20rem)]"
                  priority
                />
              </span>
            </Link>
          </header>
          <div className="flex min-h-0 flex-1 flex-col">{children}</div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
